REGION_NAME = "region_name"
ID_SERIES = "id_series"
FIRST_NAME = "first_name"
LAST_NAME = "last_name"
SEX = "sex"
BIRTHDAY = "birthday"
ID_EMITTED_AT = "id_emitted_at"
ID_EXPIRES_AT = "id_expires_at"
ID_EMITTED_BY = "id_emitted_by"

TOP_LEFT = "top_left"
BOTTOM_RIGHT = "bottom_right"
WHITELIST = "whitelist"
BLACKLIST = "blacklist"
